# Lychee configuration

exclude = [
    "http://localhost.*",
    "https://github.com/.*/pipelines.*",
    "https://gitlab.com/.*/pipelines.*",
]

# Maximum number of retries
max_retries = 3

# Wait time between retries (seconds)
retry_wait = 30

# Accept only http/https links
accept = ["https?://.+"]
