# Lychee link checker configuration

exclude = [
    "https://www.figma.com/*",
    "https://keen-pegasus-a95a6a.netlify.app/",
    ".*PUBLIC_URL.*"
]

include_extensions = [
    "md",
    "txt",
    "html",
    "htm"
]

max_retries = 3
retry_wait = 30
